# Generated by Django 3.2.16 on 2022-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thresh_temp', models.CharField(max_length=200)),
                ('thresh_humidity', models.CharField(max_length=200)),
            ],
        ),
    ]
